language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- pypy
- pypy3

env:
- TEST_SUITE="doctests"
- TEST_SUITE="foundrytest"
- TEST_SUITE="sphinx"

matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.2'
  - python: pypy3
  - env: TEST_SUITE="foundrytest"
  exclude:
  - python: '2.6'
    env: TEST_SUITE="sphinx"
  - python: '3.2'
    env: TEST_SUITE="sphinx"

before_install:
- export DOC=$(python -c "import sys; x = float(sys.version[0:3]) > 3.4 if sys.version[0]=='3'
  else float(sys.version[0:3])>2.6; sys.exit(x)")

install:
- if [ $DOC -eq 1 ]; then pip install -r requirements-doc.txt; else pip install -r
  requirements.txt; fi
- if [ $TEST_SUITE == "sphinx" ]; then pip install -r requirements-doc.txt; fi
- pip install .

script:
- make test
- if [ $(python -c "import sys; print(sys.version[0:3])") >= "3.2" ]; then make doc html; fi

after_script:
- if [ $(python -c "import sys; print(sys.version[0:3])") == "3.5" ]; then make cover; fi

deploy:
  provider: pypi
  user: althonos
  password:
    secure: tOxmKL2WfIajsSao4rVau9xLehIqfpKOm9SCwUlGREJas/D+yFYcltdamVa/kpc2PgHcmQBJxkZzEEDsAiZunm/435qWR2T01B2zB00JdtfWvnoCWEEzg/SEsy/0yS6m666P3vbdSvtfHByaavzPf5RE3ooBwsbKt3OKgS3fs91zFZwJZU6zATpBC6pzwhbt6PZeYzmZnk2AkRl8O2abPh8iHz1DGxJ3baY3ObG289W5Dp9a3sr9PVkXvLCMe04JeORTlPt43hnAy6PpnN8FSgKKLdTiMeqRcctZdH8Y90EIW8nWWoqaokNVLepxDDtf3ouy57DNyZu1FNZDlsQd7aYyUrydy7UIrMa33L7ai0hRcvKQI1ymRbO3W4opOPDcORulvYGUNLeVU886lvuLavlJ+otZClRBPV3EuO0k2eslAvwiTF8DBjB9HPuF3ZtkBgnDH7ubU1hoMi6MQvbjVThI0J7uyTVNmnS8r9/Yv02TsTl+IBHzhE3Sb8z2ZNF/Ip5UU5rbcmmvA/euShL2A+Eb0hhe/Fen3fVROl/cwcGIbkEXTurzc5xfyoLs76VOxr+HvYqA4DzxvDwhhvQSk0PTymO5T5WRj4PYbmkHeevVCsH8unva27u1CeKhVYIrWyvXwDhIK11mLzWKT2SAEVypil8YUcQpROR8vJP2yA4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: althonos/pronto
notifications:
  email:
  - althonosdev@gmail.com
