language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "pypy"
    - python: "pypy3"

install:
  - pip install -r requirements.txt
  - pip install Sphinx sphinx-rtd-theme #needed for the doc but not the actual package
  - pip install .

before_script:
  # check if documentation can be build by Sphinx with current python version.
  - export DOC=$(python -c "import sys; x = float(sys.version[0:3]) > 3.4 if sys.version[0]=='3' else float(sys.version[0:3])>2.6; sys.exit(x)") 

script:
  - python tests/doctests.py
  - if [ $DOC -eq 1 ]; then cd docs && make html; fi
