language: python

python:
  - "2.6" # Fails at install time
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  - TEST=doctests.py
  - TEST=foundrytest.py

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "pypy"
    - python: "pypy3"
    - env: TEST=foundrytest.py # Probably times out

before_install:
  # check if documentation can be build by Sphinx with current python version.
  - export DOC=$(python -c "import sys; x = float(sys.version[0:3]) > 3.4 if sys.version[0]=='3' else float(sys.version[0:3])>2.6; sys.exit(x)") 

install:
  - if [ $DOC -eq 1 ]; then pip install -r requirements-doc.txt; else pip install -r requirements.txt; fi
  - pip install .

script:
  - make test
  - if [ $DOC -eq 1 ]; then make doc html; fi

after_script:
  - if [ $(python -c "import sys; print(sys.version[0:3])") == "3.5" ]; then make cover; fi
